### PR TITLE
SIP314 fix flooding bug too much drainage

### LINKED ISSUE #314: Fix latent flooding bug
Currently, a high enough value of waterDrainFrac will drain more excess water than there is. This should be capped at "all in this time step"

### PR DESCRIPTION
**Pull request by Alomir**
## Summary

- **What**: A high enough value for waterDrainFrac will drain more excess water than exists
- **Motivation**: It's a bug!

## How was this change tested?
Added test point for the new cap
All current unit and smoke tests pass

## Related issues

- Fixes #314

## Checklist

- [x] Related issues are listed above. [PRs without an approved, related issue may not get reviewed](docs/CONTRIBUTING.md#propose-and-receive-feedback).
- [x] PR title has the issue number in it ("[#<number>] \<concise description of proposed change>")
- [x] Tests added/updated for new features (if applicable)
- [x] Documentation updated (if applicable)
- [x] `docs/CHANGELOG.md` updated with noteworthy changes
- [x] Code formatted with `clang-format` (run `git clang-format` if needed)

---

**Note**: See [CONTRIBUTING.md](../docs/CONTRIBUTING.md) for additional guidance. This repository uses automated formatting checks; if the pre-commit hook blocks your commit, run `git clang-format` to format staged changes.

### CODE REVIEW

**Comment by Alomir** [comment]
@copilot please update tests/sipnet/test_modeling/testSoilMoisture.c to cover this change

**Comment by Alomir** [comment]
Bummer!

File: src/sipnet/events.h [hunk 1]
```diff
@@ -170,6 +170,8 @@ void setupEvents(void);
  */
 int isFirstEventBefore(int year, int day);
 
+// TODO: remove this function and its call sites, sipnet:resetFluxes now
```
Comment (dlebauer) [inline src/sipnet/events.h:173]: does this warrant a separate issue?

**Review by dlebauer — APPROVED** [review]
LGTM!

File: src/sipnet/events.h (hunk 1 above)
Comment (dlebauer) [reply src/sipnet/events.h:173]: will ping in slack
